### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by seanrowland101**

### CODE REVIEW

**Review by Aramythia — CHANGES_REQUESTED** [review]
I don't see the point of updating Ayesha.py

**Comment by seanrowland101** [comment]
> I don't see the point of updating Ayesha.py

To keep consistency with the rest of the files in the github

**Comment by Aramythia** [comment]
Yea but then I have to change so much

**Comment by seanrowland101** [comment]
> Yea but then I have to change so much

So do I lol

**Pull request merged**
